[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/readiness"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[[services]]
name = "wallm-web"

[[services.cron]]
name = "daily-summary"
command = "python app/summarize_and_send_to_groups_task.py"
schedule = "0 17 * * *"